### PR TITLE
Run docker images as non-root user ('spaceros-user')

### PR DESCRIPTION
**Pull request by mjeronimo**
Also add any mising run.sh scripts. This simplifies running GUI apps and we no longer need instructions about this.

### CODE REVIEW

**Review by nuclearsandwich — COMMENTED** [review]
It seems like there are some general cleanup/fixup commits as well as updates like the addition of the devcontainer manifest among the non-root user changes. It would probably be good hygiene to break those out into independent PRs in order to consider them and the non-root user changes more easily since there's a lot of motion here.

Nothing specific jumped out on a first read. I was tempted to recommend adding `USER root` declarations where required instead of using sudo within the downstream containers since I think the usual style is to do build / setup stage as root and then create a non privileged user for container "runtime" but one container's run can be a downstream containers build and I don't have any strong technical reasons to go back and forth between root and non-root aside from clear separation between the "phases" of build and runtime.

**Comment by mjeronimo** [comment]
Sure, I'll split out a couple of the categories of changes to make it easier to review.

**Comment by mjeronimo** [comment]
Ok, I've got the other changes integrated that aren't related to changing to a non-root user ("spaceros-user"). There is only one other unrelated item, which is working around a MoveIt2 build-time issue (only a couple lines in the Dockerfile) that I didn't think was worth splitting out.

**Review by nuclearsandwich — APPROVED** [review]
Thanks for iterating and splitting out the other fixes. This looks really good!

**Pull request merged**
