### PR TITLE
Introduced a layered approach to the MoveIt2 on Space ROS build

### PR DESCRIPTION
**Pull request by mjeronimo**
* Build octomap separately since it has a special "octomap-distribution" package
* Work around a build problem with octomap/conversions.h
* Introduce a separate MoveIt2 underlay directory
* Remove repos from the moveit2_underlay.repos that are already in MoveIt2's moveit2.repos
* Pull the repos using both moveit2_underlay.repos and moveit2.repos

Fixes: https://github.com/space-ros/space-ros/issues/32

### CODE REVIEW

**Comment by wjwwood** [comment]
Is this octomap issue part of the moveit from source instructions? Seems weird.

**Comment by wjwwood** [comment]
Well, you could pull the release version of octomap, which will not contain the root of the repository, e.g.: https://github.com/ros2-gbp/octomap-release/tree/release/rolling/octomap

**Comment by wjwwood** [comment]
I was just more curious if this is reflected in the moveit2 build instructions and/or if they handle this problem some other way.

**Comment by mjeronimo** [comment]
So far, I've been building everything from source without installing release packages. I was thinking this was the way to go given the focus on static analysis, etc.; it would make the whole stack available for analysis. 

No, I haven't seen the issue mentioned in the moveit2 build instructions. From other discussions and investigation, it appears that this issue is with the octomap cmakefiles. I'll update this branch when there is a proper fix (so I don't have to do work-arounds).

**Comment by wjwwood** [comment]
I'm not talking about installing a binary, you can download the _source code_ for the released octomap from the release repository (what I linked to), and build that. That way you don't have the whole repo which has the root CMake file and other stuff like octovis which you don't need afaik.

**Comment by wjwwood** [comment]
> No, I haven't seen the issue mentioned in the moveit2 build instructions. From other discussions and investigation, it appears that this issue is with the octomap cmakefiles. I'll update this branch when there is a proper fix (so I don't have to do work-arounds).

I understand the issue is with octomap, I was just wondering if moveit2 has instructions which include building octomap from source, but I guess not since they would run into this same issue if that were the case.

**Comment by mjeronimo** [comment]
Ah, Ok, thanks. Didn't realize that.

**Comment by wjwwood** [comment]
I don't want to block you here in pursuit of "perfect", but I do think having two workspaces is a bit complicated. Maybe just cloning from the release repository rather than their source repository is enough, though that means you're not tracking their main branch any longer. However, in the case of octomap, which is pretty stable by now (AFAIK), it should be relatively safe to do so.

**Comment by mjeronimo** [comment]
Not using this approach.

**Pull request closed without merging**
